# Generated by Django 4.0.1 on 2022-02-26 17:21

from django.db import migrations, models
import django.db.models.deletion

def forwards(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True, verbose_name='имя')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='фото')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory')),
            ],
        ),
         migrations.RunPython(forwards),
    ]
